# Generated by Django 2.2.6 on 2019-12-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=250)),
                ('upvotes', models.PositiveSmallIntegerField(default=0)),
                ('downvotes', models.PositiveSmallIntegerField(default=0)),
                ('views', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('answered_on', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'ordering': ('upvotes',),
            },
        ),
    ]
