# Generated by Django 2.2.6 on 2019-12-31 18:54

from django.db import migrations, models
import inqoire.utils.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0002_auto_20191231_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=inqoire.utils.helpers.file_answer_loc),
        ),
    ]
