# Generated by Django 2.2.6 on 2020-01-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0003_answer_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
