# Generated by Django 2.2.6 on 2020-01-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0004_auto_20200104_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
