# Generated by Django 2.2.6 on 2020-01-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0005_answer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
