# Generated by Django 2.2.6 on 2019-12-31 16:46

from django.db import migrations, models
import inqoire.utils.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=400)),
                ('summary', models.CharField(blank=True, max_length=250, null=True)),
                ('link', models.URLField(blank=True, max_length=300, null=True)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True, unique=True)),
                ('file', models.ImageField(blank=True, null=True, upload_to=inqoire.utils.helpers.file_upload_loc)),
                ('is_answered', models.BooleanField(default=False)),
                ('asked_by_privacy', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Public'), (2, 'Anonymous'), (3, 'Limited')], default=1, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ('-created',),
            },
        ),
    ]
