# Generated by Django 2.2.6 on 2019-12-31 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20191231_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answered_by',
        ),
    ]
