# Generated by Django 2.2.6 on 2020-01-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='contrib_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
