# Generated by Django 2.2.6 on 2020-01-04 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contribute', '0002_contribution_contrib_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='user',
            new_name='by',
        ),
        migrations.AddField(
            model_name='contribution',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='contributors', to=settings.AUTH_USER_MODEL),
        ),
    ]
