# Generated by Django 2.2.6 on 2020-01-07 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0004_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthday',
            name='dob',
            field=models.DateField(),
        ),
    ]
