# Generated by Django 2.2.6 on 2020-01-07 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contribute', '0005_auto_20200106_1834'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BirthDay',
        ),
    ]
