# Generated by Django 2.2.6 on 2019-12-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default='This project was built as my #2 exercise with Python.', max_length=150, null=True),
        ),
    ]
