# Generated by Django 2.2.6 on 2020-01-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191231_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
