# Generated by Django 2.2.6 on 2020-01-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_activation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='token',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
