# Generated by Django 2.2.6 on 2020-01-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_activated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='free_subscription_ends_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
