# Generated by Django 2.2.6 on 2020-01-02 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_free_subscription_ends_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='joined_with_ip',
            new_name='joined_from_ip',
        ),
    ]
