# Generated by Django 2.2.6 on 2020-02-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200102_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
