# Generated by Django 2.2.6 on 2020-01-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.PositiveSmallIntegerField(choices=[(1, '<i class="la la-thumbs-up thumbs"></i>'), (-1, '<i class="la la-thumbs-down thumbs"></i>')]),
        ),
    ]
